# 连点特殊技 - 石头剪刀布
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1.6
  - op_name: "按键-特殊攻击"
    post_delay: 0.2
    repeat: 3
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10