template_name: "琉音-好评套路"
handlers:
  - states: ""
    interrupt_states: "![琉音-特殊技可用] | [自定义-琉音-投诉]{6,99}"
    sub_handlers:
      - states: "[琉音-能量]{75, 120} & ![自定义-琉音-投诉]{3,999}"
        operations:
          - op_name: "按键-切换角色"
            agent_name: "琉音"
          - operation_template: "琉音-找投诉"