handlers:
  - states: ""
    operations:
    - op_name: "设置状态"
      state: "自定义-连携跳过"
    - op_name: "设置状态"
      state: "自定义-连携换人"
    - operation_template: "连携-取消"
    - op_name: "清除状态"
      state: "按键可用-连携技"